version: '2.0'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/configs:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "AnyPassword"
      MYSQL_DATABASE:      "redmine"
    restart: always

  redmine:
    build:
      context: .
    image: redmine:local
    volumes:
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - ./redmine/data:/usr/src/redmine/files
      - ./redmine/models:/usr/src/redmine/app/models/
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    environment:
      REDMINE_DB_MYSQL:        "mysql"
      REDMINE_DB_USERNAME:     "root"
      REDMINE_DB_PASSWORD:     "AnyPassword"
      REDMINE_SECRET_KEY_BASE: "AnyKeyYouLike"
      REDMINE_PLUGINS_MIGRATE: 1
    restart: always
    
  nginx:
    image: nginx:1.15.9
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
